config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :restaurants do
    resources :reviews
  end

  root to: "restaurants#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true, format: { with: /\A[A-Z]/, message: 'has to start with a capital letter'}
	validates :cuisine, presence: true, length: { minimum: 3 }
	has_many :reviews
	belongs_to :user

	def average_rating
		return 'N/A' if reviews.none?
		reviews.average(:rating)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :authenticate_user!, except: [:index]

	def index
		@restaurants = Restaurant.all
		@review = Review.new
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new restaurant_params
		@restaurant.user = current_user
		if @restaurant.save
			redirect_to '/restaurants'
		else
			render :new
		end
	end

	def edit
		find_restaurant
	end

	def update
		@restaurant = current_user.restaurants.find params[:id]
		@restaurant.update restaurant_params
		rescue ActiveRecord::RecordNotFound
			Rails.logger.warn('WARNING: A user tried to edit a restaurant')
			flash[:notice] = 'You do not have permission to edit the restaurant: '
		ensure
			redirect_to '/restaurants'
	end

	def destroy
		@restaurant = current_user.restaurants.find params[:id]
		@restaurant.destroy

		flash[:notice] = "Successfully deleted #{@restaurant.name}"
		rescue ActiveRecord::RecordNotFound
			Rails.logger.warn('WARNING: A user tried to delete a restaurant')
			flash[:notice] = 'You do not have permission to delete the restaurant: '
		ensure
			redirect_to '/restaurants'
	end

	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :cuisine)
	end

	def find_restaurant
		@restaurant = Restaurant.find params[:id]
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		find_restaurant
		@review = Review.new
	end

	def create
		find_restaurant
		@review = @restaurant.reviews.create params[:review].permit(:thoughts, :rating)	
		redirect_to '/restaurants' unless request.xhr?
	end

	private

	def find_restaurant
		@restaurant = Restaurant.find params[:restaurant_id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def star_rating(rating)
		return rating unless rating.respond_to?(:round)

		rounded_rating = rating.round
		remainder = (5 - rounded_rating)
		# half_star = (5 - rounded_rating - remainder) floor and ceil
		("★" * rounded_rating) + ('☆' * remainder)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Yelp</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Tangerine">
	<link rel="stylesheet" href="/combo/1.17.16?/css/layouts/pricing.css">
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<nav>
		<a href='/' class='logo'>Painted Yelp</a>
		<span class='user_menu'>
			<% if user_signed_in? %>
			    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
			    <%= link_to('Edit Account', edit_user_registration_path) %>
			<% else %>
			    <%= link_to('Login', new_user_session_path) %>
			    <%= link_to('Register', new_user_registration_path) %>
			<% end %>
		</span>
	</nav>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
	<div id='error-list'>
		<h2>Errors</h2>
		<ul>
		<% @restaurant.errors.full_messages.each do |message| %>
			<li><%= message %> </li> 
		<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @restaurant do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :cuisine %>
	<%= f.text_field :cuisine %>

	<%= f.submit %>

<% end %>

app/views/restaurants/delete.html.erb
<h1>Confirm Restaurant for Deletion</h1>

<%= render 'form' %>

app/views/restaurants/edit.html.erb
<h1>Update a Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="pure-g">
	<% if @restaurants.any? %>
				<% @restaurants.each do |r| %>
					<div class="pure-u-1 pricing-tables pure-u-md-1-3">
						<div class="pricing-table pricing-table-free">
							<div class="pricing-table-header">
								<h2><%= r.name %></h2> <br>
								(<%= r.cuisine %>)<br>
							</div>
							<span class="pricing-table-price">
	                        	<%= star_rating(r.average_rating) %> 
	                        	<span>Average rating</span>
	                    	</span>
							<% if current_user %>
								<%= link_to "Edit #{r.name}", edit_restaurant_path(r.id) %><br>
							<% end %>
							<% if current_user %>
								<%= link_to "Delete #{r.name}", restaurant_path(r.id), method: :delete, 'data-confirm' => "Are you sure you want to delete this?" %><br>
							<% end %>			
							<%= link_to "Review #{r.name}", new_restaurant_review_path(r.id) %><br>
							<ul class='pricing-table-list'>
								<% r.reviews.each do |review| %>
									<li><%= review.thoughts %> (<%= star_rating review.rating %>)</li>
								<% end %>
							</ul>

							<%= form_for [r, @review] do |f| %>
								<p><%= f.label :thoughts, 'Write a review:' %></p>
								<p><%= f.text_area :thoughts %></p>

								<p><%= f.label :rating %>
								<%= f.select :rating, 1..5 %></p>

								<%= f.submit %>

							<% end %>
						</div>
					</div>
				<% end %>

	<% else %>
		<h1>No restaurants yet</h1>
	<% end %>
</div>
<%= link_to 'Create Restaurant', new_restaurant_path, id: "", class: "" %>

app/views/restaurants/new.html.erb
<h1>Create a New Restaurant</h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>

	<%= f.label :rating %>
	<%= f.select :rating, 1..5 %>

	<%= f.submit %>

<% end %>